language: go
go:
  - 1.6
  - tip

os:
  - linux
  - osx

script:
  - go test -coverprofile=coverage.txt ./lib/randstr
  - go test ./cmd/randstr
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
